### PR TITLE
Added James' talk

### PR DESCRIPTION
**Pull request by jamestripp**
Added the R and Docker talk I presented

### CODE REVIEW

**Comment by hturner** [comment]
I added a pandoc extension to `_site.yml` so we can have external links opening in a new tab, e.g. 

`[Slides](https://jamestripp.github.io/RandDocker/){target="_blank"}`

cc @ccamara

**Comment by ccamara** [comment]
Hi, thanks both for your contributions. I have not had time to test this, but I am wondering why [9d76077](https://github.com/WarwickRUG/wrug_website/pull/25/commits/9d760775dd5601aa8940e1a835ec959124ddbfed) modifies so many files. Is this desired?

**Comment by ccamara** [comment]
Well, anyway, I see it's been already merged! 😆

**Comment by jamestripp** [comment]
Thanks both :)

**Comment by hturner** [comment]
Oh there were a lot of whitespace changes - there is probably a way to avoid this, but I didn't think it was too important.

**Pull request merged**
